chat/urls.py
from django.urls import path
from .views import (
    lobby,
    rooms,
    chat,
    all_messages,
    create_room,
    edit_room,
    delete_room,
    announcements_list,
    edit_announcement,
    create_announcement,
    delete_announcement,
    roadmap,
    all_roadmaps,
    create_roadmap,
    edit_roadmap,
    delete_roadmap,
    create_document,
    delete_document,
    create_category,
    delete_category,
)

urlpatterns = [
    # Sala
    path("lobby/", lobby, name="lobby"),
    path("rooms/", rooms, name="rooms"),
    path("chat/<str:room_id>/", chat, name="chat"),
    path("criar_sala/", create_room, name="criar_sala"),
    path("editar_sala/<str:room_id>/", edit_room, name="editar_sala"),
    path("deletar_sala/<str:room_id>/", delete_room, name="deletar_sala"),
    path("adicionar_categoria/", create_category, name="adicionar_categoria"),
    path("deletar_categoria/<str:category_id>/", delete_category, name="deletar_categoria"),
    # Aviso
    path("avisos/<str:room_id>/", announcements_list, name="avisos"),
    path("criar_aviso/<str:room_id>/", create_announcement, name="criar_aviso"),
    path("editar_aviso/<str:room_id>/<str:announcement_id>/", edit_announcement, name="editar_aviso"),
    path("deletar_aviso/<str:room_id>/<str:announcement_id>/", delete_announcement, name="deletar_aviso"),
    # Roadmap
    path("roadmap/<str:room_id>/<str:roadmap_id>/", roadmap, name="roadmap"),
    path("roadmaps/<str:room_id>/", all_roadmaps, name="roadmaps"),
    path("criar_roadmap/<str:room_id>/", create_roadmap, name="criar_roadmap"),
    path("editar_roadmap/<str:room_id>/<str:roadmap_id>/", edit_roadmap, name="editar_roadmap"),
    path("deletar_roadmap/<str:room_id>/<str:roadmap_id>/", delete_roadmap, name="deletar_roadmap"),
    # Documento
    path("criar_documento/<str:room_id>/<str:roadmap_id>/", create_document, name="criar_documento"),
    path("deletar_documento/<str:room_id>/<str:document_id>/", delete_document, name="deletar_documento"),
    # Mensagens
    path("mensagens/<str:room_id>/", all_messages, name="mensagens"),
]

projeto/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("usuarios.urls")),
    path("chat/", include("chat.urls")),
    re_path(r"^download/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),
    re_path(r"^ckeditor/", include("ckeditor_uploader.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor_uploader.fields import RichTextUploadingField


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Room(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=255)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    members = models.ManyToManyField(User, related_name="rooms")
    max_participants = models.IntegerField(default=50)
    image = models.ImageField(upload_to="static/img")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Announcement(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=1000)
    created_by = models.ForeignKey(User, on_delete=models.PROTECT)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Roadmap(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=1000, null=True)
    content = RichTextUploadingField()
    created_by = models.ForeignKey(User, on_delete=models.PROTECT)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Document(models.Model):
    title = models.CharField(max_length=100)
    file = models.FileField(upload_to="media/", default="")
    roadmap = models.ForeignKey(Roadmap, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

chat/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from ckeditor.widgets import CKEditorWidget

from chat.models import Document, Roadmap


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]


class RoadmapForm(forms.ModelForm):
    class Meta:
        model = Roadmap
        fields = ["title", "description", "content"]
        widgets = {"content": CKEditorWidget()}


class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ["title", "file"]

chat/views.py
from django.shortcuts import get_object_or_404, render, redirect, reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from chat.forms import DocumentForm, RoadmapForm
from .models import Announcement, Room, Category, Roadmap, Document
from .filters import RoomFilter
from .utils import check_if_user_can_join
from .message_manager import (
    delete_messages_from_firebase,
    delete_messages_from_json,
    retrieve_messages_from_json,
    retrieve_messages_from_firebase,
)


@login_required(login_url="/login/")
def lobby(request):
    room_filter = RoomFilter(request.GET, queryset=Room.objects.all())
    context = {
        "room_filter": room_filter,
    }
    return render(request, "lobby.html", context)


@login_required(login_url="/login/")
def rooms(request):
    user = request.user
    user_rooms = Room.objects.filter(members__in=[user])
    context = {
        "user_rooms": user_rooms,
    }
    return render(request, "rooms.html", context)


@login_required(login_url="/login/")
def chat(request, room_id):
    if not check_if_user_can_join(request.user, room_id):
        messages.error(request, "A sala já atingiu seu limite máximo")
        return render(request, "lobby.html")
    else:
        chat_messages = retrieve_messages_from_json(room_id)
        announcements = Announcement.objects.filter(room=room_id)[:7]
        roadmaps = Roadmap.objects.filter(room=room_id)[:4]
        context = {
            "room_id": room_id,
            "messages": chat_messages,
            "announcements": announcements,
            "roadmaps": roadmaps,
        }
        return render(request, "chat.html", context)


@login_required(login_url="/login/")
def all_messages(request, room_id):
    all_messages = retrieve_messages_from_firebase(room_id)
    context = {
        "room_id": room_id,
        "all_messages": all_messages,
    }
    return render(request, "mensagens.html", context)


@login_required(login_url="/login/")
def announcements_list(request, room_id):
    all_announcements = Announcement.objects.filter(room=room_id)
    context = {
        "announcements": all_announcements,
        "room_id": room_id,
    }
    return render(request, "avisos.html", context)


@login_required(login_url="/login/")
def create_announcement(request, room_id):
    room = Room.objects.get(id=room_id)
    if request.method == "POST":
        title = request.POST.get("titulo", None)
        description = request.POST.get("descricao", None)
        new_annoucement = Announcement(title=title, description=description, created_by=request.user, room=room)
        new_annoucement.save()
        return redirect(reverse("avisos", args=[room_id]))
    context = {"room_id": room_id}
    return render(request, "criar_aviso.html", context)


@login_required(login_url="/login/")
def edit_announcement(request, room_id, announcement_id):
    announcement = Announcement.objects.get(id=announcement_id)
    if request.method == "POST":
        title = request.POST.get("titulo", None)
        description = request.POST.get("descricao", None)
        announcement.title = title
        announcement.description = description
        announcement.save()
        return redirect(reverse("avisos", args=[room_id]))
    context = {
        "room_id": room_id,
        "announcement": announcement,
    }
    return render(request, "editar_aviso.html", context)


@login_required(login_url="/login/")
def delete_announcement(request, room_id, announcement_id):
    if request.method == "POST":
        announcement = Announcement.objects.get(id=announcement_id)
        announcement.delete()
        return redirect(reverse("avisos", args=[room_id]))


@login_required(login_url="/login/")
def create_room(request):
    categories = Category.objects.all()
    if request.method == "POST":
        name = request.POST.get("nome", None)
        description = request.POST.get("descricao", None)
        category_input = request.POST.get("categoria", None)
        category = Category.objects.get(name=category_input)
        max_participants = request.POST.get("limite", None)
        image = request.FILES.get("imagem")
        new_room = Room(
            name=name, description=description, category=category, max_participants=max_participants, image=image
        )
        new_room.save()
        return redirect("/")
    context = {"categories": categories}
    return render(request, "criar_sala.html", context)


@login_required(login_url="/login/")
def edit_room(request, room_id):
    categories = Category.objects.all()
    room = get_object_or_404(Room, id=room_id)
    if request.method == "POST":
        name = request.POST.get("nome", None)
        description = request.POST.get("descricao", None)
        category_input = request.POST.get("categoria", None)
        category = Category.objects.get(name=category_input)
        image = request.FILES.get("imagem")
        room.name = name
        room.description = description
        room.category = category
        if image:
            room.image = image
        room.save()
        return redirect("/")
    context = {
        "room": room,
        "categories": categories,
    }
    return render(request, "editar_sala.html", context)


@login_required(login_url="/login/")
def delete_room(request, room_id):
    room = Room.objects.get(id=room_id)
    room.delete()
    delete_messages_from_json(room_id)
    delete_messages_from_firebase(room_id)
    return redirect("/")


@login_required(login_url="/login/")
def roadmap(request, room_id, roadmap_id):
    roadmap = Roadmap.objects.get(id=roadmap_id)
    context = {
        "room_id": room_id,
        "roadmap": roadmap,
    }
    return render(request, "roadmap.html", context)


@login_required(login_url="/login/")
def all_roadmaps(request, room_id):
    roadmaps = Roadmap.objects.filter(room=room_id).order_by("-created")
    form = DocumentForm()
    context = {
        "room_id": room_id,
        "roadmaps": roadmaps,
        "form": form,
    }
    return render(request, "roadmaps.html", context)


@login_required(login_url="/login/")
def create_roadmap(request, room_id):
    room = Room.objects.get(id=room_id)
    if request.method == "POST":
        form = RoadmapForm(request.POST)
        if form.is_valid():
            my_form_data = form.save(commit=False)
            my_form_data.created_by = request.user
            my_form_data.room = room
            my_form_data.save()
            return redirect(reverse("roadmaps", args=[room_id]))
    else:
        form = RoadmapForm()
    context = {
        "room_id": room_id,
        "form": form,
    }
    return render(request, "criar_roadmap.html", context)


@login_required(login_url="/login/")
def edit_roadmap(request, room_id, roadmap_id):
    room = Room.objects.get(id=room_id)
    roadmap = Roadmap.objects.get(id=roadmap_id)
    if request.method == "POST":
        form = RoadmapForm(request.POST, instance=roadmap)
        if form.is_valid():
            my_form_data = form.save(commit=False)
            my_form_data.created_by = request.user
            my_form_data.room = room
            my_form_data.save()
            return redirect(reverse("roadmaps", args=[room_id]))
    else:
        form = RoadmapForm(instance=roadmap)
    context = {
        "room_id": room_id,
        "roadmap": roadmap,
        "form": form,
    }
    return render(request, "editar_roadmap.html", context)


@login_required(login_url="/login/")
def delete_roadmap(request, room_id, roadmap_id):
    roadmap = Roadmap.objects.get(id=roadmap_id)
    roadmap.delete()
    return redirect(reverse("roadmaps", args=[room_id]))


@login_required(login_url="/login/")
def create_document(request, room_id, roadmap_id):
    roadmap = Roadmap.objects.get(id=roadmap_id)
    if request.method == "POST":
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            document = form.save(commit=False)
            document.roadmap = roadmap
            document.save()
            return redirect(reverse("roadmaps", args=[room_id]))
    else:
        form = DocumentForm()
    roadmaps = Roadmap.objects.filter(room=room_id).order_by("-created")
    context = {
        "room_id": room_id,
        "roadmaps": roadmaps,
        "form": form,
    }
    return render(request, "roadmaps.html", context)


@login_required(login_url="/login/")
def delete_document(request, room_id, document_id):
    document = Document.objects.get(id=document_id)
    document.delete()
    return redirect(reverse("roadmaps", args=[room_id]))


@login_required(login_url="/login/")
def create_category(request):
    categories = Category.objects.all()
    if request.method == "POST":
        name = request.POST.get("name", None)
        Category.objects.create(name=name)
        return redirect("criar_sala")
    context = {
        "categories": categories,
    }
    return render(request, "adicionar_categoria.html", context)


@login_required(login_url="/login/")
def delete_category(request, category_id):
    category = Category.objects.get(id=category_id)
    category.delete()
    previous_url = request.META.get("HTTP_REFERER")
    return redirect(previous_url)

chat/templates/adicionar_categoria.html
{% extends 'main.html' %}
{% load static %}

{% block 'title' %}Adicionar Categoria{% endblock %}

{% block content %}

<div class="col m-5 text-amber-500 font-bold">
    <div class="row">
        <h3 class="text-3xl font-bold mb-5">Adicionar Categoria</h3>
    </div>

    <div class="row flex">
        <form method="post" action="{% url 'adicionar_categoria' %}">
            {% csrf_token %}

            <div class="col-sm-6 mb-3">
                <label class="form-label mb-2">Categoria:</label>
                <input type="text" class="form-control" name="name" id="name" required>
            </div>

            <div class="mb-3">
                <button type="submit"
                    class="bg-amber-500 w-32 hover:bg-amber-600 font-bold py-2 px-4 text-fuchsia-700 rounded">Criar</button>
            </div>
        </form>
    </div>
    <div class="row w-1/2">
        {% if categories %}
        <table class="table ml-4 my-4 text-amber-500">
            <thead>
                <tr>
                    <th class="text-2xl">Categorias disponíveis</th>
                </tr>
            </thead>
            <tbody>
                {% for category in categories %}
                <tr>
                    <td class="my-2">{{ category.name }}</td>
                    <td class="my-2"><a href="{% url 'deletar_categoria' category.id %}">Deletar</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>
    <a href="{% url 'criar_sala' %}"><button
            class="bg-amber-500 w-32 hover:bg-amber-600 font-bold py-2 px-4 text-fuchsia-700 rounded">Voltar</button></a>
</div>

{% endblock content %}

chat/templates/avisos.html
{% extends 'main.html' %}
{% load static %}
{% block 'title' %}Avisos{% endblock %}

{% block content %}
<div class="col m-5 text-amber-500 font-bold">
    <div class="row">
        <h3 class="text-3xl font-bold mb-5">Avisos</h3>
    </div>

    {% if request.user.is_superuser %}
    <div class="mb-3">
        <a class="bg-amber-500 w-48 hover:bg-amber-600 font-bold py-2 px-2 text-fuchsia-700 rounded"
            href="{% url 'criar_aviso' room_id %}" role="button">Criar novo aviso</a>
    </div>
    {% endif %}

    <div class="row mb-5">
        <ul>
            {% for announcement in announcements %}
            <div class="py-3">
                <li class="text-2xl mb-2">Título: {{ announcement.title }}</li>
                <li class="mb-2">Descrição: {{ announcement.description }}</li>
                <li class="text-sm mb-4">Por: {{ announcement.created_by }}</li>
                {% if request.user.is_superuser %}
                <li class="underline"><a href="{% url 'editar_aviso' room_id announcement.id %}">Editar</a>
                </li>
                <li class="underline cursor-pointer"><a data-bs-toggle="modal"
                        data-bs-target="#exampleModal{{announcement.id}}">Deletar
                    </a></li>
            </div>

            <!-- Modal -->
            <div class="modal fade" id="exampleModal{{announcement.id}}" tabindex="-1" role="dialog"
                aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title text-black" id="exampleModalLabel">"{{ announcement.title }}"</h5>
                            <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body text-black">
                            Deseja mesmo deletar o aviso "{{ announcement.title }}?"
                        </div>
                        <div class="modal-footer">
                            <form method="post" action="{% url 'deletar_aviso' room_id announcement.id %}">
                                {% csrf_token %}
                                <button type="submit"
                                    class="bg-red-500 hover:bg-red-600 p-2 rounded font-bold text-white">Deletar</button>
                            </form>
                            <button type="button" class="bg-blue-500 hover:bg-blue-600 p-2 rounded font-bold text-white"
                                data-bs-dismiss="modal">Voltar</button>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}
            <hr>
            {% endfor %}
        </ul>
    </div>

    <a href="{% url 'chat' room_id %}"><input type="button"
            class="bg-amber-500 w-48 hover:bg-amber-600 font-bold py-2 px-2 text-fuchsia-700 rounded"
            value="Voltar"></a>
</div>
{% endblock content %}

chat/templates/chat.html
{% extends 'main.html' %}
{% load static %}
{% block 'title' %}Painel Chat{% endblock %}
{% block content %}

<style>
  .message-text,
  .announcement-class {
    word-break: break-word;
  }
</style>

<div class="row m-5 text-amber-500 font-bold">
  <div class="row">
    <h3 class="text-3xl font-bold mb-5">Chat virtual</h3>
  </div>

  <div class="row flex flex-row">
    <div class="col-2 h-96 bg-fuchsia-700 rounded-2xl text-center shadow-2xl">
      <p class="text-2xl my-2">Últimos avisos</p>
      <hr>
      <ul class="list-group">
        {% for announcement in announcements %}
        <li class="p-1 bg-fuchsia-600 announcement-class">
          <a data-bs-toggle="modal" data-bs-target="#exampleModal{{announcement.id}}"
            class="card-link cursor-pointer">{{announcement.title}}</a>
          <div class="modal fade" id="exampleModal{{announcement.id}}" tabindex="-1" role="dialog"
            aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">{{announcement.title}}</h5>
                  <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  {{announcement.description}}
                </div>
                <div class="modal-footer">
                  <button type="button"
                    class="bg-amber-500 w-100 hover:bg-amber-600 font-bold py-2 px-4 text-fuchsia-700 rounded"
                    data-bs-dismiss="modal">Voltar</button>
                </div>
              </div>
            </div>
          </div>
        </li>
        <hr>
        {% endfor %}
        <li><a href="{% url 'avisos' room_id %}">Ver todos...</a></li>
      </ul>
    </div>
    <div class="col-10 h-96 bg-fuchsia-500 rounded-2xl shadow-2xl">
      <form id="form">
        <div id="scrollbar" style="overflow-y: scroll; height: 340px;">
          <div class="m-2" id="messages">
            {% for message in messages %}
            <div>
              <p class="message-text p-2 my-1 bg-fuchsia-200 text-fuchsia-700 rounded">
                {{ message.sender }}: {{ message.text }}
                <small>| {{ message.time}}</small>
              </p>
            </div>
            {% endfor %}
          </div>
        </div>
        <div class="input-group mb-3">
          <input type="text" name="messageInput" class="form-control" required>
          <button class="btn btn-outline-info" type="submit" id="button-addon2">Enviar</button>
        </div>
      </form>
    </div>
  </div>

  <div class="row mt-2 py-5 flex flex-row flex-wrap">
    <div class="col bg-fuchsia-600 rounded-2xl shadow-2xl text-center">
      <p class="text-2xl my-2">Guias de estudo</p>
      <div class="row flex flex-row flex-wrap">
        {% if roadmaps %}
        {% for roadmap in roadmaps %}
        <div class="bg-fuchsia-700 rounded shadow-2xl p-4 m-2 w-1/4">
          <ul>
            <li class="text-2xl text-center bg-fuchsia-800 my-2 hover:bg-fuchsia-950">
              <a href="{% url 'roadmap' room_id roadmap.id  %}">{{ roadmap.title }}</a>
            </li>
            <li class="text-center bg-fuchsia-800 my-2">
              {% if roadmap.document_set.exists %}
              {% for document in roadmap.document_set.all %}
              <a href="{{ document.file.url }}" download>
            <li class="text-center bg-fuchsia-800 my-2">
              <ion-icon class="mr-2" name="document"></ion-icon>{{ document.title}}
            </li>
            </a>
            {% endfor %}
            {% else %}
            <p>Nenhum documento disponível para este guia</p>
            {% endif %}
            </li>
          </ul>
          {% endfor %}
          {% else %}
          <p class="mb-3">Nenhum guia de estudos disponível</p>
          {% endif %}
        </div>
        <a href="{% url 'roadmaps' room_id %}" class="my-2">Ver todos...</a>
      </div>
    </div>
  </div>
</div>

{% if request.user.is_superuser %}
<div class="col m-5">
  {% if messages %}
  <a class="bg-amber-500 w-48 my-2 hover:bg-amber-600 font-bold py-2 px-4 text-fuchsia-700 rounded"
    href="{% url 'mensagens' room_id %}">Ver todas as mensagens...</a>
  {% endif %}
  <a class="bg-amber-500 w-48 my-1 hover:bg-amber-600 font-bold py-2 px-4 text-fuchsia-700 rounded"
    href="{% url 'editar_sala' room_id %}">Editar sala</a>
  <a class="bg-amber-500 w-48 my-1 hover:bg-amber-600 font-bold py-2 px-4 text-fuchsia-700 rounded cursor-pointer"
    data-bs-toggle="modal" data-bs-target="#deleteModal">Deletar sala</a>
</div>
{% endif %}

<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Deletar sala</h5>
        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Deseja mesmo deletar a sala?
        {{room_id}}
      </div>
      <div class="modal-footer">
        <form method="post" action="{% url 'deletar_sala' room_id %}">
          {% csrf_token %}
          <button type="submit" class="bg-red-500 hover:bg-red-600 p-2 rounded font-bold text-white">Deletar</button>
        </form>
        <button type="button" class="bg-blue-500 hover:bg-blue-600 p-2 rounded font-bold text-white"
          data-bs-dismiss="modal">Cancelar</button>
      </div>
    </div>
  </div>
</div>
</div>


<script src="https://code.jquery.com/jquery-3.7.0.js" integrity="sha256-JlqSTELeR4TLqP0OG9dxM7yDPqX1ox/HfgiSLBj8+kM="
  crossorigin="anonymous"></script>
<script>
  let path = window.location.pathname;
  let pathParts = path.split('/');
  let roomName = pathParts[pathParts.length - 2];

  let url = `ws://${window.location.host}/ws/socket-server/${roomName}/`

  const chatSocket = new WebSocket(url)

  let form = document.getElementById('form')
  form.addEventListener('submit', (e) => {
    e.preventDefault()
    let text = e.target.messageInput.value
    let sender = "{{ request.user.username|escapejs }}"
    let room = "{{ room_id }}"

    chatSocket.send(JSON.stringify({
      'text': text,
      'sender': sender,
      'room': room
    }))
    form.reset()
  })

  chatSocket.onmessage = function (e) {
    let data = JSON.parse(e.data)

    if (data.type === 'chat') {
      let messages = document.getElementById('messages')
      let scrollbar = document.getElementById('scrollbar')

      messages.insertAdjacentHTML('beforeend', `<div>
                                <p class="message-text p-2 my-1 bg-fuchsia-200 text-fuchsia-700 rounded">${data.sender}: ${data.text} <small>|  ${data.time}</small></p>
                            </div>`)

      scrollbar.scrollTop = messages.scrollHeight;
    }
  }
</script>
{% endblock content %}

chat/templates/roadmaps.html
{% extends 'main.html' %}
{% load static %}
{% block 'title' %}RoadMaps{% endblock %}

{% block content %}

<div class="col m-5 text-amber-500 font-bold">
    <div class="row">
        <h3 class="text-3xl font-bold mb-5">Guias de Estudo</h3>
    </div>

    {% if request.user.is_superuser %}
    <a class="bg-amber-500 w-48 hover:bg-amber-600 font-bold py-2 px-4 text-fuchsia-700 rounded"
        href="{% url 'criar_roadmap' room_id  %}">Criar Guia de estudo</a>
    {% endif %}

    <div class="row flex flex-row flex-wrap my-5">
        {% if roadmaps %}
        {% for roadmap in roadmaps %}
        <div class="bg-fuchsia-700 rounded shadow-2xl p-4 m-2 w-1/3">
            <ul>
                <li class="text-2xl text-center bg-fuchsia-800 my-2 hover:bg-fuchsia-950">
                    <a href="{% url 'roadmap' room_id roadmap.id  %}">{{ roadmap.title }}</a>
                </li>
                <li class="mb-2">{{ roadmap.description }}</li>
                <li class="mb-2">Criado por: {{ roadmap.created_by }}</li>
                <hr>
                <li class="mb-2">Arquivos:</li>
                {% if roadmap.document_set.exists %}
                {% for document in roadmap.document_set.all %}
                <a href="{{ document.file.url }}" download>
                    <li class="text-center bg-fuchsia-800 my-2 flex justify-between">
                        <ion-icon class="mr-2" name="document"></ion-icon>{{ document.title}}
                        {% if request.user.is_superuser %}
                        <a class="cursor-pointer" href="{% url 'deletar_documento' room_id document.id %}">
                            <ion-icon name="close-circle"></ion-icon>
                        </a>
                        {% endif %}
                    </li>
                </a>
                {% endfor %}
                {% else %}
                <p>Nenhum documento disponível para este guia</p>
                {% endif %}
                </li>
                {% if request.user.is_superuser %}
                <a type="button" data-bs-toggle="modal" data-bs-target="#exampleModal{{roadmap.id}}">Adicionar
                    documento</a>
                <!-- Modal -->
                <div class="modal fade text-black" id="exampleModal{{roadmap.id}}" tabindex="-1" role="dialog"
                    aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">Adicionar documento</h5>
                                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <form action="{% url 'criar_documento' room_id roadmap.id %}" method="post"
                                    enctype="multipart/form-data">
                                    {% csrf_token %}
                                    {{ form.as_p }}
                                    <button type="submit"
                                        class="bg-green-500 mt-2 hover:bg-green-600 p-2 rounded font-bold text-white"
                                        data-bs-dismiss="modal">Salvar</button>
                                </form>
                            </div>
                            <div class="modal-footer">
                                <button type="button"
                                    class="bg-blue-500 hover:bg-blue-600 p-2 rounded font-bold text-white"
                                    data-bs-dismiss="modal">Voltar</button>
                            </div>
                        </div>
                    </div>
                </div>
                {% endif %}
            </ul>
            {% endfor %}
            {% else %}
            <p class="mb-3">Nenhum guia de estudos disponível</p>
            {% endif %}
        </div>
    </div>
</div>
<a href="{% url 'chat' room_id %}"
    class="bg-amber-500 w-48 hover:bg-amber-600 font-bold m-5 py-2 px-4 text-fuchsia-700 rounded">Voltar</a>
<script src="{% static 'js/forms.js' %}"></script>

{% endblock content %}